### PR TITLE
solved issue no 1124

### PR DESCRIPTION
**Pull request by Krish-bhardwaj**
## Description
Hi i have solved this issue ( translated (https://developers.italia.it/en/legal-notice )  into english)

### CODE REVIEW

**Comment by developers-italia-droid** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
>  issue solved 1124 translated legal notice page to english
- subject may not be empty
- type may not be empty</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> issue #1124 solved
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3057b87bdcf941b354feef62101e67523c8e24dd
</p>

**Comment by Krish-bhardwaj** [comment]
Hi @developers-italia-droid i have fixed this issue and have changed the commit msg also still getting 
image
just this one error plz guide me @ruphy @cloudify @gunzip

**Comment by bfabio** [comment]
Hello @Krish-bhardwaj, thanks for the PR!

The bot is complaining about the commit message format. We use and enforce conventional commits:

https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md#commit-messages and https://www.conventionalcommits.org/en/v1.0.0/

**Comment by bfabio** [comment]
#1156 was merged, but we should compare this translation as well to see if we can merge some improvements

**Pull request closed without merging**
