### PR TITLE
[#718] fix search input autofocus

### LINKED ISSUE #718: The search modal should autofocus the input field
The search field is not focused by default when the search modal is opened, requiring the user to click on it.
Tested on Firefox and Chromium.

Peek 28-09-2020 13-38

### PR DESCRIPTION
**Pull request by maurovitale**
## Description

As already mentioned in #718, this PR tackles:
Fix the search input autofocus, triggering the focus event when the user clicks on the search icon, so the user can start to directly type as requested

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes #718

### CODE REVIEW

**Review by bfabio — COMMENTED** [review]
Hey @maurovitale, thanks for the PR! Can't we just use the `autofocus` attribute?

**Comment by maurovitale** [comment]
Hi @bfabio, I had tried as the first option to do what u suggested but didn't work, so I figured out with this solution

**Comment by maurovitale** [comment]
Hi @bfabio is it ready to be merged to the master branch or I need to do some fix?

**Comment by bfabio** [comment]
@maurovitale I'd prefer a simpler solution and I don't like that `setTimeout` very much. Maybe there's something stealing the focus when it shouldn't and it's preventing `autofocus` to work.

**Comment by maurovitale** [comment]
Hi @bfabio, here there is the solution directly from the bootstrap website: 
_Due to how HTML5 defines its semantics, the autofocus HTML attribute has no effect in Bootstrap modals. To achieve the same effect, use some custom JavaScript:_ (https://getbootstrap.com/docs/4.0/components/modal/)

The **modal** class is applied to the **searchModal** div where our input is contained so is not working.
I changed the code to get the **searchModal** show event and trigger the focus event, now it's working. Not timeout anymore :)  I'll commit it in a moment.

**Review by bfabio — APPROVED** [review]
@maurovitale Great work! :rocket:

**Pull request merged**
