### PR TITLE
feat: improve the get-involved page

### LINKED ISSUE #974: Improve the get-involved page
The https://developers.italia.it/en/get-involved should be improved:

* Remove the first box of text "Get Involved"
* Move the "Partecipate" section to the bottom
* Change the title and remove the extra buttons in the "Contribute to the enabling platforms" section
* Clarify the "Participate in development of public software" section

### PR DESCRIPTION
**Pull request by bfabio**
Reword unclear titles and simplify the Get involved page.

Fix #974.

### CODE REVIEW

**Comment by bfabio** [comment]
Just the Italian page for now. I'll port the changes to the English one as well when there's consensus, after the review.

**Comment by libremente** [comment]
Thanks @bfabio I kinda like it, the message is clearer now and the CTA is easily reachable.
Just my 2 cents: I'm not particularly happy with the three blue layers at the bottom of the page, see screenshot:
Schermata 2021-05-06 alle 22 30 38

It's not a real issue though, just my personal opinion

**Comment by bfabio** [comment]
Possible options

# Uniform the color for the box (site-wide)
image

# Remove the duplicate Slack section for that page
image

wdyt?

On a different note, I checked and those colors are all in the Design palette, so we are good on that front.

**Review by sebbalex — APPROVED** [review]
I'd personally keep original color scheme and same content for footer section

**Pull request merged**
