### PR TITLE
Issue #722/ 767 actual fix

### PR DESCRIPTION
**Pull request by joneskj55**
## Description

As already mentioned in #722/ 767, this PR tackles:
* This fixes the button background color on it/software

In particular, on hover the background now changes to your standard site blue color, while the button text is white and very visible. 

*PLEASE IGNORE/ DELETE PREVIOUS PULL REQUEST AS THIS ONE IS A CLEANER FIX*

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes # 722
- Fixes #767

### CODE REVIEW

**Review by bfabio — CHANGES_REQUESTED** [review]
Hello @joneskj55, thanks for the patch! We should probably use the existing classes provided by Bootstrap / Bootstrap Italia for that button.

**Comment by joneskj55** [comment]
@bfabio Loud and clear.

**Comment by joneskj55** [comment]
Hi @bfabio this latest commit fixes the button utilizing bootstrap/ bootstrap Italia classes as requested. Please let me know if this will suffice.

**Review by bfabio — APPROVED** [review]
@jenkin Thanks a lot for your time :tada: lgtm!

**Pull request merged**
