### PR TITLE
fix issue 768 viewport overflow

### PR DESCRIPTION
**Pull request by joneskj55**
## Description

As already mentioned in #768 , this PR tackles:
* The issue of the viewport moving horizontally on mobile devices
* Added `overflow-x: hidden` to the body in main.scss

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes # 768

### CODE REVIEW

**Review by bfabio — CHANGES_REQUESTED** [review]
Hi @joneskj55, I think we should rather find what's overflowing and fix that.

**Comment by joneskj55** [comment]
> Hi @joneskj55, I think we should rather find what's overflowing and fix that.

Thanks @bfabio I get the message.

**Comment by joneskj55** [comment]
Hey @bfabio It looks like .container is what is overflowing. Since that is a Bootstrap class I thought that we could just hide the overflow for the `body` to solve this issue. If thats no good let me know, I will try to find another solution.

**Comment by bfabio** [comment]
Hey @joneskj55, I think finding why `.container` is overflowing and fixing that would be a cleaner solution.

**Comment by ameybhavsar24** [comment]
@bfabio this can be closed now

**Comment by bfabio** [comment]
Fixed by #814.

**Pull request closed without merging**
