### PR TITLE
feat: use the component for software thumbnails

### LINKED ISSUE #641: Do we really want the first screenshot to be the preferred thumbnail?
The current order of preference for software thumbnails is:

1. First screenshot
2. Logo
3. Placeholder

Do we really want the first screenshot to be the preferred one? Screenshots are usually indiscernible at small sizes and not very appealing in general.

Popular stores use the logo:

* https://flathub.org/home
* https://play.google.com/store/apps
* https://snapcraft.io/store

### LINKED ISSUE #915: Use the CatalogueItem everywhere in the site for software items
As discussed in #743, it would be nice to use `CatalogueItem` everywhere and replace the logic in `display-logo.html` with it.

We should make Jekyll generate a custom element <catalogue-item> in place of what we do now, and use its attributes to pass down the data (like description, name, logo, etc.) to CatalogueItem's React props.

cc @emilioSp @UchihaCFC

### PR DESCRIPTION
**Pull request by bfabio**
Fix #641 
Fix #915

### CODE REVIEW

**Comment by bfabio** [comment]
HTML-Proofer complains, but I'm not sure this is due to a new publiccode that breaks the current build as well. I suppose we can wait for tomorrow's build and see.

**Comment by bfabio** [comment]
@sebbalex fixed, ready for review :+1:

**Comment by sebbalex** [comment]
Looking at PA's page I found:
Screenshot from 2021-05-27 15-39-43

**Comment by bfabio** [comment]
@sebbalex thanks, fixed

**Review by sebbalex — APPROVED** [review]

**Pull request merged**
