### PR TITLE
Registrati su Slack button modified

### LINKED ISSUE #1299: Slack registration link looks ugly and not rendered
Any `/piattaforma` page shows the `[(registrati su Slack)](https://slack.developers.italia.it/)` link in an ugly way, it somehow looks as if an element is not rendered around it. 
Schermata 2022-08-19 alle 09 14 50

I believe we should find a better way to represent that link, with a button or anything like that.

### PR DESCRIPTION
**Pull request by ziriuz84**
## Description

This PR tackles:

* Fixes the aspect of "Registrati su Slack" buttons

## Checklist

* [x] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Ready for review! :rocket:

## Fixes

Fixes #1299

### CODE REVIEW

**Comment by developers-italia-droid** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>There is a problem with the commit message
> Registrati su Slack button modified
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b1fd50ced5616ec5587c039fbbdc3c01c33a5984
</p>

**Comment by ziriuz84** [comment]
I saw the error by @developers-italia-droid, but I don't understand where is the problem :man_shrugging:

**Comment by bfabio** [comment]
@ziriuz84 thanks! Gonna review it ASAP.

Don't worry about the bot: we can ignore that warning.

**Comment by ziriuz84** [comment]
Is it ok as this?

**Review by bfabio — APPROVED** [review]

**Comment by bfabio** [comment]
@ziriuz84 merged thanks :tada:

There's are also the English version of those pages, if you'd like to give it a go ;)

**Comment by ziriuz84** [comment]
Ok, no problem

**Comment by ziriuz84** [comment]
Do you prefer another PR or I continue on this?

**Comment by bfabio** [comment]
@ziriuz84 a new one would be good

**Pull request merged**
