### PR TITLE
Fix [#737] [#719]

### LINKED ISSUE #737: Ugly vertical spacing in website name
**Describe the bug**

`Developers Italia` has too much vertical spacing and no margin from the logo. This is very ugly IMHO. We should find a way to fix it. 
WhatsApp Image 2020-10-02 at 10 46 43(1)

### PR DESCRIPTION
**Pull request by twopill**
## Description

As already mentioned in #ISSUE_NUMBER, this PR tackles:
*  Fix the vertical spacing name in mobile version of website
* Fix Software name lenght

## Checklist

- [**X**] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [**X**] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [**X**] Have you written new tests for your core changes, as applicable?
- [**X**] Have you successfully ran tests with your changes locally?
- [**X**] XReady for review! :rocket:

## Fixes

- Fixes #737 #719

### CODE REVIEW

**Review by bfabio — CHANGES_REQUESTED** [review]
Hey @twopill, can you please split the fix for #719 to another PR?

**Comment by twopill** [comment]
> Hey @twopill, can you please split the fix for #719 to another PR?

Hi @bfabio i have created a new pull request.
But i don't know how to delete commit from this pull request, sorry

**Comment by bfabio** [comment]
@twopill you can remove the last commit with 
`git reset --hard HEAD~`
`git push --force`

**Comment by libremente** [comment]
Hi @twopill, any news on this PR? Thanks!

**Comment by twopill** [comment]
> Hi @twopill, any news on this PR? Thanks!

Yep i create now a new pull request: [https://github.com/italia/developers.italia.it/pull/790](https://github.com/italia/developers.italia.it/pull/790)

**Pull request closed without merging**
