### PR TITLE
Deleted absolute of projectlist__listing__url

### LINKED ISSUE #733: Software text overlap
**Describe the bug**
As seen below, there is an overlapping of the "Leggi di più" text over the software description.
WhatsApp Image 2020-10-02 at 09 52 50(2)

**To Reproduce**
1. Go to the software page with a mobile browser

### PR DESCRIPTION
**Pull request by Guiguerreiro39**
To fix an overlapping text issue in mobile, deleting position: absolute in the projectlist__listing__url style fixes the issue.

## Description

As already mentioned in #733, this PR tackles:
- Overlapping of the url over the text in the project listing

Solution:
- Added a *media* class to *projectlist__listing__url* style class in *main.scss* for 768px screens and lower with *position: unset* to only remove *position: absolute* in small devices.

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes #733

### CODE REVIEW

**Comment by bfabio** [comment]
@Guiguerreiro39 Thanks for the patch, unfortunately this breaks the alignment of the links:

# Before the patch
https://developers.italia.it/en/search?page=1&sort=relevance#
image

# After the patch
https://deploy-preview-766--developers-italia.netlify.app/en/search?page=1&sort=relevance#
image

**Comment by Guiguerreiro39** [comment]
Hello @bfabio , I've added some changes that hopefully fix that issue.

**Comment by bfabio** [comment]
Thanks @Guiguerreiro39! Can you rebase on master please?

@sebbalex @libremente This looks good, but my CSS is weak. Do you think there might be side effects with this approach?

**Comment by Guiguerreiro39** [comment]
Hey!
Is it all good or should I make any change?

**Review by bfabio — APPROVED** [review]

**Comment by bfabio** [comment]
@Guiguerreiro39 Looks like we already merged #778 which also included the fix for this. Thank you for your time :heart:

**Pull request closed without merging**
