### PR TITLE
[Issue #623] Update to Jekyll 4.x

### PR DESCRIPTION
**Pull request by UchihaCFC**
## Description

Seems that there are no problems updating to version 4.1.1 of Jekyll. With the exception of `hawkins`, but I have seen that it is not necessary to continue using it because version 4 includes live reload, so I have removed it to continue with the update. You can see more about it here: https://github.com/awood/hawkins/issues/17

When doing the `docker-compose up --build` I have seen that it generates new jekyll cache files in the `.jekyll-cache` folder, so I have added it to the `.gitignore` file.

After all I have run `docker-compose up` and everything seems to work fine.

It would be necessary to check that everything is going well  with with Netlify ?

## Checklist

- [X] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [X] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [X] Have you written new tests for your core changes, as applicable?
- [X] Have you successfully ran tests with your changes locally?
- [X] Ready for review! :rocket:

## Fixes
- Issue #623 - Trying update Jekyll to 4.x version

### CODE REVIEW

**Comment by sebbalex** [comment]
Please consider that in PR environment we skip both the Elasticsearch indexing and Github issue retrieving. We should test them as well.

**Comment by bfabio** [comment]
@UchihaCFC Thanks :tada: Can you please rebase it on master and squash the commits to just one?

**Comment by UchihaCFC** [comment]
I have been able to update the branch successfully from master but I'm having problems with squash from merging master on several occasions, maybe it would be better to do a new pull request with only the concrete commit?

**Comment by bfabio** [comment]
@UchihaCFC Of course, you can do that if you feel more comfortable.

**Comment by UchihaCFC** [comment]
@bfabio I closed this pull request by #779 with one only commit

**Pull request closed without merging**
