### PR TITLE
(#702) Updated name of button in header

### LINKED ISSUE #702: Button does not have a name
**Describe the bug**
``` 
Error: This element has role of "button" but does not have a name available to an accessibility API. Valid names are: element content, aria-label undefined, aria-labelledby undefined.                                                                                                                                   
   ├── WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.Name
   ├── #main > header > div:nth-child(1) > div:nth-child(1) > div > div:nth-child(1) > a:nth-child(4)
   └── <a href="#" class="d-inline-block d-lg-none py-2 text-white" data-activeid="slimDropdown" role="button" data-activate-element=""> <svg class="icon i...</a>
```

We should probably add a name to the element.
Tested with pa11y

### PR DESCRIPTION
**Pull request by mishrajiharsh219**
## Description

As already mentioned in #ISSUE_NUMBER, this PR tackles:
* ...
* ...
* ...

In particular, the ...

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes #702

### CODE REVIEW

**Comment by bfabio** [comment]
Hi @masihtak, the warning in the bug report is a little bit misleading. It's not related to the `name` HTML attribute. Take a look at https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=412#qr-ensure-compat-rsv, we most likely want an `aria-label`.

**Comment by masihtak** [comment]
@bfabio I didn't add this!

**Comment by bfabio** [comment]
Sorry, @mishrajiharsh219, autocomplete misled me :)

**Comment by mishrajiharsh219** [comment]
ok i will correct it

**Pull request closed without merging**
