### PR TITLE
Fix Software name lenght exceeds column width 

### LINKED ISSUE #719: Software name lenght exceeds column width
**Describe the bug**
Schermata da 2020-09-28 18-43-26

As you can see from the screenshot, the name is too long and overlaps other elements on its right. This is probably due to the fact that the dots make it impossible to naturally split it with a return.

## Reproduce
Look for that software in the search results page

### PR DESCRIPTION
**Pull request by twopill**
## Description

As already mentioned in #ISSUE_NUMBER, this PR tackles:
* I have tried to split my pr, sorry 
* Fix Software Name

In particular, the ...

## Checklist

- [ X] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ X] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ X] Have you written new tests for your core changes, as applicable?
- [ X] Have you successfully ran tests with your changes locally?
- [ X] Ready for review! :rocket:

## Fixes

- Fixes #719

### CODE REVIEW

**Comment by twopill** [comment]
@bfabio I tried to split, is correct now?

**Comment by bfabio** [comment]
Hi @twopill, thanks.

Looks like the bug is still there: https://deploy-preview-755--developers-italia.netlify.app/it/search?keyword=rer&page=0&sort=relevance

**Comment by twopill** [comment]
> Hi @twopill, thanks.
> 
> Looks like the bug is still there: https://deploy-preview-755--developers-italia.netlify.app/it/search?keyword=rer&page=0&sort=relevance

Yep i see, but i look the inspector and my fix dosn't appear.
Because when i edit the inspector and add my fix: 
[https://ibb.co/wrjrGBp](https://ibb.co/wrjrGBp) **<-- image**

**Comment by bfabio** [comment]
Unfortunately there's still duplication in the way we handle thumbnails. The relevant code for search thumbnails is in `assets/js/search.handlebars`.

**Comment by twopill** [comment]
> Unfortunately there's still duplication in the way we handle thumbnails. The relevant code for search thumbnails is in `assets/js/search.handlebars`.

I  have create a new pull request:[https://github.com/italia/developers.italia.it/pull/790]( https://github.com/italia/developers.italia.it/pull/790)

**Pull request closed without merging**
