### PR TITLE
Rearrange circleci builds

### PR DESCRIPTION
**Pull request by libremente**
This PR is intended to rearrange the circleci builds:
* Delete the `_buildscripts` dir together with the files in it.
* Move the contents of those two scripts in the makefile.
* Insert the `gem install bundler` in the Makefile. NB: this *may* be suboptimal.
* Copy a folder to the remote server
@sebbalex

### CODE REVIEW

**Comment by libremente** [comment]
I guess it's better to work on this PR now and then later on proceed with the docker @sebbalex

**Comment by libremente** [comment]
Is this still needed @sebbalex seeing the novel infrastructure?

**Comment by sebbalex** [comment]
@libremente I'd start from this as base branch and build new infrastructure upon this.

**Comment by sebbalex** [comment]
Actually netlify is failing because of this:
`10:53:19 AM: /usr/local/bin/build: line 112: ./_buildscripts/build-swagger.sh: No such file or directory
`
After merge we need to rearrange also there.

**Comment by LucaPrete** [comment]
Can't we fix it BEFORE merging, since it triggers the error?

Il giorno ven 20 mar 2020 alle ore 11:10 Alessandro Sebastiani <
notifications@github.com> ha scritto:

**Comment by sebbalex** [comment]
> Can't we fix it BEFORE merging, since it triggers the error?

I will take care of it now

**Pull request merged**
