### PR TITLE
[#737] fixs the header vertical space on mobile devices

### LINKED ISSUE #737: Ugly vertical spacing in website name
**Describe the bug**

`Developers Italia` has too much vertical spacing and no margin from the logo. This is very ugly IMHO. We should find a way to fix it. 
WhatsApp Image 2020-10-02 at 10 46 43(1)

### PR DESCRIPTION
**Pull request by maurovitale**
## Description

As already mentioned in #737, this PR tackles:
Fixs the alignment problem of the logo and the search icon on mobile devices

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?
- [ ] Ready for review! :rocket:

## Fixes

- Fixes #737

### CODE REVIEW

**Comment by maurovitale** [comment]
Hi @bfabio, maybe this PR is ready to be merged. The tests failed on mixed content but seems to be a problem on the master branch.

**Review by bfabio — CHANGES_REQUESTED** [review]
Hello @maurovitale, thank you for your work.

You're right, the test failing is not caused by the PR, we're going to fix that ASAP.

This looks good. Can we split the line as late as possible, like the live site is doing right now?

# Live Site
2-prod

# Pull request
1-pr




Regarding the PR, here's

**Comment by maurovitale** [comment]
Hi @bfabio, I updated it now, let me know if it's ok

**Review by bfabio — APPROVED** [review]

**Comment by bfabio** [comment]
@maurovitale Thank you for your work, merged!

**Pull request merged**
