### PR TITLE
[WIP] [#773] Cartografia catastale Agenzia delle Entrate

### LINKED ISSUE #773: Add API Cartografia catastale
# Issue content

Add cartografia catastale API

### PR DESCRIPTION
**Pull request by ioggstream**
## Description
As already mentioned in #ISSUE_NUMBER, this PR tackles:
* add cartografia catastale API

- Fixes #773

### CODE REVIEW

**Comment by libremente** [comment]
Looks OK apart from a few typos highlighted here: https://github.com/teamdigitale/api-openapi-samples/pull/60
However, I really don't like the final page look, opened #775 to handle it

**Comment by ioggstream** [comment]
@libremente this page is used to showcase the API Catalog to the agency. They are working on the logo and if the process goes on successfully they will serve the yaml file from their own platform :)

**Comment by developers-italia-droid** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> Cartografia catastale Agenzia delle Entrate
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f89bd035f4ea531fc8852bf622ffa3370fc0ef79
</p>

**Comment by ioggstream** [comment]
@mfortini @sebbalex @libremente non mergiare finché non è fixato il logo di AdE #961

**Review by sebbalex — APPROVED** [review]

**Pull request merged**
