### PR TITLE
Fix #271

### LINKED ISSUE #271: Otello img preview is slightly smaller than others
Otello img preview is slightly smaller than others. As such, the line is broken. See screenshot:
schermata da 2019-02-18 18-37-10

### PR DESCRIPTION
**Pull request by FredBonux**
Solution based on search result style.
Closes #271

### CODE REVIEW

**Comment by libremente** [comment]
Thanks @FredBonux! This looks fine for me. Let's wait for @sebbalex review then I'll merge.

**Comment by FredBonux** [comment]
@sebbalex I see, I'm going to fix that in a few days.

**Comment by FredBonux** [comment]
@sebbalex It turns out that was quite simple, I did add a medium-and-down breakpoint in order to increase the height of the images on mobiles but, as you saw, it stretches the pictures. 
I've removed that to fully match the search result dimensions.

**Comment by libremente** [comment]
@sebbalex Yes, same here on FF70 emulating different layouts (e.g., iPhone X/XS). This behaviour is not present on the current version of the website. Could you please test again @FredBonux? Thanks!

**Comment by FredBonux** [comment]
@libremente @sebbalex I've found the same "problem" into the search result page. I could fix it, but maybe it's better to open another issue to fix it on both pages.

**Comment by libremente** [comment]
Hi @FredBonux, I still see issues with this PR also in the standard desktop view, see below:
Schermata 2019-11-05 alle 16 32 51

**Comment by FredBonux** [comment]
@libremente I've added more breakpoints, now it should work on any device size.

**Comment by sebbalex** [comment]
Thanks @FredBonux !

**Pull request merged**
