### PR TITLE
Fix responsive layout issues

### LINKED ISSUE #414: Visual issue when browser window width is in range 991-768 pixels
Visual issue when browser window width is in range 991-768 pixels:
developers italia it-bug

 (OSX Chrome v.77, Safari v.13.01)

### PR DESCRIPTION
**Pull request by masihtak**
Fix responsive layout issues for the medium and large screen sizes.
Fix #414

### CODE REVIEW

**Comment by libremente** [comment]
Could you please test this locally @luciopileggi ? Thanks

**Comment by luciopileggi** [comment]
> Could you please test this locally @luciopileggi ? Thanks

LGTM

developers-italia-issue-

**Comment by libremente** [comment]
Thanks!
Personally, I'd like to merge https://github.com/italia/developers.italia.it/pull/378 before which implements the new version of BSI before merging this one since it looks like there are quite some delicate changes in this. @sebbalex

**Comment by sebbalex** [comment]
Yes, I agree with @libremente, in those days I will work on #378 and later we will evaluate this again!

**Comment by masihtak** [comment]
I believe this wont break anything as I also updated `$italia` to the `$primary`.

**Comment by libremente** [comment]
Hi @masihtak, could you please further elaborate your work? In particular, it is not very clear to me why you worked *also* on the footer section. Is this relevant for #414? Thanks!

**Comment by masihtak** [comment]
Hi @libremente . as I discussed with @biancini I found more layout issues for the med devices which I addressed in this PR!
layout-issue

As you can see in the image there are some layout issue for the Partipa and the footer section beside what mentioned in #414

**Comment by libremente** [comment]
Thanks @masihtak, merged!

**Pull request merged**
