### PR TITLE
feat: add link to landingUrl in software's page

### LINKED ISSUE #1031: Use publiccode.yml landingURL variable to create a link to the project site
While working on the publication of GlobaLeaks by means of the publiccode.yml descriptor i've noticed that the variable ``landingURL`` (https://github.com/globaleaks/GlobaLeaks/blob/main/publiccode.yml#L5) apprears not used anywhere on the [profile of the software](https://developers.italia.it/it/software/globaleaks-globaleaks-f22648.html).

This ticket is to propose to use the value of the landingURL variable in order to create a link "Site" on the right sidebar to be shown over the link "Documentation

Screenshot_2021-06-29 GlobaLeaks - Developers Italia

Originally reported at: https://github.com/publiccodeyml/publiccode.yml/issues/99

### PR DESCRIPTION
**Pull request by bfabio**
Fix #1031.

### CODE REVIEW

**Comment by bfabio** [comment]
## Before
image


## After
image

**Review by sebbalex — APPROVED** [review]

**Comment by libremente** [comment]
This string is different from the other one, it looks like a CTA "Vai al sito". I am thinking about other ways to express it, something like "Sito Web del progetto", which is more neutral than the CTA proposed. WDYT  @bfabio?

**Comment by bfabio** [comment]
@libremente good point!

**Comment by bfabio** [comment]
@libremente 

image
image

**Pull request merged**
