### PR TITLE
Fix graphic issue on search page results

### PR DESCRIPTION
**Pull request by lucaros97**
Just aligned-center text on page result. This is good when we have to show the "no result" message and also when you find something.

### CODE REVIEW

**Comment by libremente** [comment]
Hi @lucaros97 , did you test this under all the breakpoints (mobile etc.)?

**Comment by lucaros97** [comment]
Yes, works perfectly in all breakpoints (especially on mobile/tablet i thinks look better on text-center)

**Comment by libremente** [comment]
Great @lucaros97 I'll try to test this locally tonight and let you know 👍

**Comment by libremente** [comment]
Thanks @lucaros97, merged! 🎉

**Pull request merged**
