### PR TITLE
[#501] Open external links safely in new tab

### LINKED ISSUE #501: Open external links in new tab/window
The external link should be opened in a new tab/window

### PR DESCRIPTION
**Pull request by masihtak**
## Description

As already mentioned in #ISSUE_NUMBER, this PR tackles:
Open external links in new tab with security to prevent [tabnapping ](https://en.wikipedia.org/wiki/Tabnabbing) and other phishing attacks.
This PR does not cover 100% of external links! I need to spend more time fixing others including the documentation links.

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ ] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes #501

### CODE REVIEW

**Comment by bfabio** [comment]
Hello @masihtak, can you rebase this one on master please?

**Comment by sebbalex** [comment]
> Hello @masihtak, can you rebase this one on master please?

Or if you need assistance feel free to ask for it :)

**Comment by masihtak** [comment]
Hello @bfabio I pushed changes with the Atom and it mess up

**Comment by bfabio** [comment]
@masihtak Are you on [our slack](https://slack.developers.italia.it/)? Let's get in touch there

**Review by bfabio — COMMENTED** [review]
I'm not sure we want `noreferrer` for .italia.it sites. @libremente WDYT?

**Comment by libremente** [comment]
> I'm not sure we want `noreferrer` for .italia.it sites. @libremente WDYT?

Yes, we don't want it. Could you please correct it @masihtak? Thanks!

**Pull request closed without merging**
