### PR TITLE
feat: add new open issues pages

### LINKED ISSUE #970: Add a new issues search page
Add a new issues search page, in both languages, to prepare for the can refactoring of the  current `to-do` page.

The page should take parameters in the querystring to filter for Platforms and languages.

### PR DESCRIPTION
**Pull request by bfabio**
Add new open issues pages in both languages (/it/attivita, /en/issues)

Fix #970.

### CODE REVIEW

**Comment by bfabio** [comment]
https://developers-ita-git-fork-bfabio-issuespage-dip-trasformaz-4cbae2.vercel.app/it/attivita
https://developers-ita-git-fork-bfabio-issuespage-dip-trasformaz-4cbae2.vercel.app/en/issues

Wdyt about the names?

**Comment by libremente** [comment]
I'm not particularly fond on using letters with accents and removing it in the URL, however I don't have particular suggestions right now.

**Comment by bfabio** [comment]
We could use "issues" for Italian as well, which is closer to the developer's expectations.

**Comment by sebbalex** [comment]
I'd use "Issues" for italian version too, I think it is closer to a developer's approach

**Review by ruphy — APPROVED** [review]

**Review by sebbalex — APPROVED** [review]

**Review by astagi — APPROVED** [review]

**Pull request merged**
