### PR TITLE
remove cloud platform for now

### PR DESCRIPTION
**Pull request by ruphy**
## Checklist

* [x] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Ready for review! :rocket:

### CODE REVIEW

**Comment by developers-italia-droid** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> remove cloud platform for now

Signed-off-by: Riccardo Iaconelli <riccardo@teamdigitale.governo.it>
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a297f2908f63babaff12566ef8a709b17f84c3fb
</p>

**Comment by libremente** [comment]
@ruphy WDYT about this? https://github.com/italia/developers.italia.it/blob/344eb9ecc045af5e580cdd97e32ed806d30961b2/assets/js/projects.js#L52-L59

**Comment by ruphy** [comment]
> @ruphy WDYT about this?
> 
> https://github.com/italia/developers.italia.it/blob/344eb9ecc045af5e580cdd97e32ed806d30961b2/assets/js/projects.js#L52-L59

NO idea where this is used or where it comes from. guessing it's somehow related to the page with the open issues...

**Review by libremente — APPROVED** [review]
LGTM

**Pull request merged**
