### PR TITLE
Pull request for issue: "More tags" button in the homepage has wrong …

### LINKED ISSUE #760: "More tags" button in the homepage has wrong style
The "More tags" button at https://developers.italia.it/en has different style than the rest of the buttons:

image

it should be blue and with more padding.

### PR DESCRIPTION
**Pull request by Guiguerreiro39**
…style #760

I've just copied the styling of the other buttons and replaced the class that the a element previously had.

## Description

As already mentioned in #760 , this PR tackles:

- Button "More Tags" has different styling from the other buttons.
- To tackle this issue I've copied the styling from the previous buttons and replaced the existing class for the copied ones, making the styling the same as the rest.
Capture

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

## Fixes

- Fixes #760

### CODE REVIEW

**Comment by bfabio** [comment]
Hello @Guiguerreiro39, thanks for  the PR! Can you also remove the unused rules of that class from CSS, please?

**Comment by Guiguerreiro39** [comment]
> 
> 
> Hello @Guiguerreiro39, thanks for the PR! Can you also remove the unused rules of that class from CSS, please?

Hello, hopefully is ready now! Sorry for that 👍

**Review by bfabio — APPROVED** [review]
Thanks for your work @Guiguerreiro39, lgtm! :tada:

**Review by sebbalex — APPROVED** [review]
:rocket:

**Comment by libremente** [comment]
Please squash and merge @bfabio

**Review by libremente — APPROVED** [review]

**Pull request merged**
